export const pathObj = {
    LOGIN:'/adminlogin',
    COACH:'/getcoach',
    ATHLETE:'/getathlete',
    FORGOT_PASSWORD:'/admin-forgotpassword',
    FORGOT_VERIFY:'/admin-forgotpassword/getreset',
    RESET_PASSWORD:'/admin-resetpassword',
    ADD_COACH:'/coachsign',
    ADD_ATHLETE:'/athletesign',
    ADD_TEAM:'/addteam',
    ADD_PLAYER:'/addplayer',
    UPDATE_COACH:'/update-coach',
    UPDATE_STATUS:'/update-status',
    UPDATE_ATHLETE_STATUS:'/update-athlete-status',
    UPDATE_TEAM_STATUS:'/update-team-status',
    UPDATE_PLAYER_STATUS:'/update-player-status',
    UPDATE_ATHLETE:'/update-athlete',
    UPDATE_TEAM:'/update-team',
    UPDATE_PLAYER:'/update-player',
    UPDATE_PRIVACY_POLICY:'/update-privacy-policy',
    DELETE_COACH:'/delete-coach',
    DELETE_ATHLETE:'/delete-athlete',
    DELETE_TEAM:'/delete-team',
    DELETE_PLAYER:'/delete-player',
    GET_TEAM: "getteams",
    GET_PLAYER: "getplayer",
    GET_COUNT: "getcount",
    UPDATE_ADMIN: "update-admin",
    GET_ADMIN: "getadmin",
    CHANGE_ADMIN_PASSWORD: "change-admin-password",
    FILTER_DATA_BY_DATE_PLAYERS: "filter-players",
    FILTER_DATA_BY_DATE_ATHLETE: "filter-athlete",
    FILTER_DATA_BY_DATE_TEAMS: "filter-teams",
    FILTER_DATA_BY_DATE_STATIC: "filter-static-content",
    FILTER_DATA_BY_DATE_COACH: "filter-coach",
    GET_PRIVACY_POLICY: "privacy-policy"
  }
  